package app.trollfoss.ui

import app.trollfoss.domain.RoomKind
import app.trollfoss.domain.Txt
import app.trollfoss.domain.txt

/** The few words of Mitt hus, in nynorsk and bokmål. The builder is made of pictures; these are for descriptions and the one question. */
object SM {
    val previewRoom = Txt("Sjå rommet før du byggjer", "Se rommet før du bygger")
    val buildThisRoom = Txt("Bygg dette rommet", "Bygg dette rommet")
    val build = txt("Bygg")
    val buildHouse = txt("Bygg huset")
    val rooms = txt("Rom")
    val floor = txt("Bygg ein etasje til", "Bygg en etasje til")
    val look = txt("Utsjånad", "Utseende")
    val party = txt("Innflyttingsfest")
    val partyTab = txt("Fest")
    val done = txt("Ferdig")
    val goInside = txt("Gå inn", "Gå inn")
    val tearDown = txt("Riv rommet?")
    val tearDownBody = txt("Alle møblane blir lagde i lageret.", "Alle møblene blir lagt i lageret.")
    val tearDownYes = txt("Riv")
    val tearDownNo = txt("Behald", "Behold")
    val chooseHouse = txt("Vel eit hus", "Velg et hus")
    val myHouse = txt("Mitt hus")
    val allBuilt = txt("Alle romma står", "Alle rommene står")
    val needRooms = txt("Du treng to rom først", "Du trenger to rom først")
    val upstairsFirst = txt("Riv rommet oppe først", "Riv rommet oppe først")
    val paint = txt("Måling", "Maling")
    val upstairs = txt("Oppe")
    val downstairs = txt("Nede")
    val outside = txt("Ut")
    val inside = txt("Inn")
    val anotherFloor = txt("Etasje")
    val chooseSlot = txt("Vel ein plass", "Velg en plass")
    val chooseRoom = txt("Vel rommet")
    val buildBelow = txt("Bygg rommet nede først")
    val wallColours = txt("Veggfarge")
    val roof = txt("Tak")
    val roofColours = txt("Takfarge")
    val doors = txt("Dør")
    val windows = txt("Vindauge", "Vinduer")
    val extras = txt("Pynt")
    val floorReady = txt("Etasjen er klar")
    val furnish = txt("Møblar", "Møbler")
    val wallpaper = txt("Tapet")
    val flooring = txt("Golv", "Gulv")
    val storage = txt("Lager")
    val deleteStored = txt("Legg i papirkorg", "Legg i papirkurv")
    val undoDelete = txt("Angre sletting", "Angre sletting")
    val trash = txt("Papirkorg", "Papirkurv")
    val restoreStored = txt("Hent tilbake")
    val emptyTrash = txt("Ingen ting i papirkorga", "Ingen ting i papirkurven")
    val groundFloor = txt("Første etasje", "Første etasje")
    val upperFloor = txt("Andre etasje", "Andre etasje")
    val houseYard = txt("Hagen")
    val youAreHere = txt("Du er her")
    val buildingSlot = txt("Byggjeplass", "Byggeplass")
    val buildNext = txt("Bygg neste rom")
    val playInRoom = txt("Leik i rommet", "Lek i rommet")
    val houseOverview = txt("Husoversikt")
    val hall = txt("Gang")
    val placeFull = txt("Gjer plass ved å leggje noko i Lager", "Gjør plass ved å legge noe i Lager")
    val buildBeforeFurnishing = txt("Bygg eit rom først", "Bygg et rom først")
    val tidy = txt("Rydd")

    fun template(i: Int): Txt = when (i) {
        0 -> txt("Hytte")
        1 -> txt("Villa")
        2 -> txt("Tårnhus")
        else -> txt("Gamalt bondehus", "Gammelt bondehus")
    }

    fun kind(k: RoomKind): Txt = when (k) {
        RoomKind.LIVING -> txt("Stove", "Stue")
        RoomKind.KITCHEN -> txt("Kjøken", "Kjøkken")
        RoomKind.DINING -> txt("Spisestove", "Spisestue")
        RoomKind.BEDROOM -> txt("Soverom")
        RoomKind.KIDS -> txt("Barnerom")
        RoomKind.BATH -> txt("Bad")
        RoomKind.LIBRARY -> txt("Bibliotek")
        RoomKind.WORKSHOP -> txt("Verkstad", "Verksted")
        RoomKind.MUSIC -> txt("Musikkrom")
        RoomKind.GREENHOUSE -> txt("Drivhus")
    }
}
