package app.trollfoss.ui

import app.trollfoss.domain.First
import app.trollfoss.domain.FirstGroup
import app.trollfoss.domain.Txt

/** Words for first-time discoveries, the gift parcel and the waterfall on the map. */
object SO {
    val newFirst = Txt("Ny oppdaging", "Ny oppdagelse")
    val firsts = Txt("Oppdagingar", "Oppdagelser")
    val parcel = Txt("Gåve. Trykk for å opne", "Gave. Trykk for å åpne")
    val fallLabel = Txt("Trollfossen: kor langt du har kome", "Trollfossen: hvor langt du har kommet")
    val notYet = Txt("Ikkje oppdaga enno", "Ikke oppdaget ennå")
    val found = Txt("Oppdaga!", "Oppdaget!")
    val dig = Txt("Grav", "Grav")

    fun group(g: FirstGroup): Txt = when (g) {
        FirstGroup.DRIVE -> Txt("Køyre", "Kjøre")
        FirstGroup.PLAY -> Txt("Leik", "Lek")
        FirstGroup.FRIENDS -> Txt("Venner", "Venner")
        FirstGroup.LIFE -> Txt("Kvardag", "Hverdag")
        FirstGroup.WORLD -> Txt("Verda", "Verden")
    }

    fun first(f: First): Txt = when (f) {
        First.TRACTOR -> Txt("Køyrde traktor", "Kjørte traktor")
        First.BOAT -> Txt("Tuta med båten", "Tutet med båten")
        First.SUBMARINE -> Txt("Dykka med ubåten", "Dykket med ubåten")
        First.BUMPER_CAR -> Txt("Køyrde radiobil", "Kjørte radiobil")
        First.BUS -> Txt("Køyrde vennebussen", "Kjørte vennebussen")
        First.TANDEM -> Txt("Sykla tandem", "Syklet tandem")
        First.TOY_TRAIN -> Txt("Køyrde leiketog", "Kjørte leketog")
        First.VACUUM_RIDE -> Txt("Reid på støvsugaren", "Red på støvsugeren")
        First.BALLOON -> Txt("Flaug med ballongen", "Fløy med ballongen")
        First.SKY_ISLAND -> Txt("Landa på Skyøya", "Landet på Skyøya")
        First.BUBBLE_POP -> Txt("Sprengde ei boble", "Sprakk en boble")
        First.PILLOW_LAUNCH -> Txt("Skaut med putekastaren", "Skjøt med putekasteren")
        First.MARBLES -> Txt("Klinkekula kom fram", "Klinkekula kom fram")
        First.COLOUR_SPRAY -> Txt("Sprøyta farge", "Sprøytet farge")
        First.POPCORN -> Txt("Laga popcorn", "Laget popkorn")
        First.PUMP -> Txt("Pumpa opp noko", "Pumpet opp noe")
        First.PHOTO -> Txt("Tok eit portrett", "Tok et portrett")
        First.MINI_LIFT -> Txt("Køyrde miniheisen", "Kjørte miniheisen")
        First.WINDMILL -> Txt("Sette vindmølla i gang", "Satte vindmøllen i gang")
        First.SEESAW -> Txt("Vippa på vippa", "Vippet på vippen")
        First.PUPPETS -> Txt("Spela dokketeater", "Spilte dukketeater")
        First.PICNIC -> Txt("Heldt piknik", "Holdt piknik")
        First.CRANE -> Txt("Løfta med kranen", "Løftet med kranen")
        First.CONVEYOR -> Txt("Starta transportbandet", "Startet transportbåndet")
        First.BUILD_TABLE -> Txt("Bygde ei vogn", "Bygde en vogn")
        First.WATER_CHANNEL -> Txt("Sende vatn i renna", "Sendte vann i renna")
        First.WATER_WHEEL -> Txt("Fekk vasshjulet til å gå", "Fikk vannhjulet til å gå")
        First.RAIN_CLOUD -> Txt("Laga regnsky", "Laget regnsky")
        First.MIRROR -> Txt("Grimas i spegelen", "Grimase i speilet")
        First.HOVER -> Txt("Fekk noko til å sveve", "Fikk noe til å sveve")
        First.PORTAL -> Txt("Gjekk gjennom portalen", "Gikk gjennom portalen")
        First.OBSTACLE -> Txt("Tok hinderbana", "Tok hinderløypa")
        First.APPLE_HARVEST -> Txt("Hausta eit eple", "Høstet et eple")
        First.REPAIR_LIGHT -> Txt("Reparerte lyset", "Reparerte lyset")
        First.SECRET_DOOR -> Txt("Fann ei hemmeleg dør", "Fant en hemmelig dør")
        First.STAMP_ART -> Txt("Stempla kunst", "Stemplet kunst")
        First.HANG_ART -> Txt("Hengde opp kunst", "Hengte opp kunst")
        First.CABLE_CAR -> Txt("Køyrde taubane", "Kjørte taubane")
        First.DIVING_BELL -> Txt("Dykka med klokka", "Dykket med klokka")
        First.DIGGER -> Txt("Grov med gravemaskina", "Gravde med gravemaskinen")
        First.TREASURE_TABLE -> Txt("Ringde på skattebordet", "Ringte på skattebordet")
        First.HUG -> Txt("Ein god klem", "En god klem")
        First.HIGH_FIVE -> Txt("High five!", "High five!")
        First.HOLD_HANDS -> Txt("Heldt handa", "Holdt hånden")
        First.PET -> Txt("Fekk eit kjæledyr", "Fikk et kjæledyr")
        First.LIVING_TEDDY -> Txt("Bamsen vakna", "Bamsen våknet")
        First.BAND -> Txt("Starta eit band", "Startet et band")
        First.PARTY -> Txt("Heldt fest", "Holdt fest")
        First.SNOWMAN -> Txt("Laga snømann", "Laget snømann")
        First.SANDCASTLE -> Txt("Bygde sandslott", "Bygde sandslott")
        First.COOK -> Txt("Laga mat", "Laget mat")
        First.EAT -> Txt("Åt noko godt", "Spiste noe godt")
        First.BATH -> Txt("Tok eit bad", "Tok et bad")
        First.SLEEP -> Txt("Gjekk og la seg", "Gikk og la seg")
        First.READ -> Txt("Las ei bok", "Leste en bok")
        First.PHONE -> Txt("Ringde nokon", "Ringte noen")
        First.BRUSH_TEETH -> Txt("Pussa tennene", "Pusset tennene")
        First.THROW_BALL -> Txt("Kasta ball", "Kastet ball")
        First.CATCH_BALL -> Txt("Fanga ballen", "Fanget ballen")
        First.TIDY -> Txt("Rydda", "Ryddet")
        First.PAINT_ROOM -> Txt("Måla rommet", "Malte rommet")
        First.BUILD_ROOM -> Txt("Bygde eit rom", "Bygde et rom")
        First.FIRST_TRIP -> Txt("Første tur", "Første tur")
        First.TRIP_5 -> Txt("Besøkte fem stader", "Besøkte fem steder")
        First.TRIP_12 -> Txt("Besøkte tolv stader", "Besøkte tolv steder")
        First.TREASURE_BOX -> Txt("Fylte skattekista", "Fylte skattekisten")
        First.ATTIC_CHEST -> Txt("Fann skatt på loftet", "Fant skatt på loftet")
        First.PEEK_TROLL -> Txt("Fanga trollet som titta fram", "Fanget trollet som tittet fram")
    }
}
